### ISSUE TITLE
Error: Cannot find module '@opendal/lib-win32-x64-msvc'

### ISSUE THREAD

**Issue by sovzzz** [bxb100/action-upload#69]
```
Error: Cannot find module '@opendal/lib-win32-x64-msvc'
Require stack:
- D:\a\_actions\bxb100\action-upload\main\dist\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:[15](https://github.com/sovzzz/SPT-AKI-SERVER-WEEKLY-BUILD/actions/runs/5500675136/jobs/10023737957#step:9:16))
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:[18](https://github.com/sovzzz/SPT-AKI-SERVER-WEEKLY-BUILD/actions/runs/5500675136/jobs/10023737957#step:9:19))
    at Object.7533 (D:\a\_actions\bxb100\action-upload\main\webpack:\upload-action\node_modules\@vercel\ncc\dist\ncc\@@notfound.js:1:1)
    at __nccwpck_require__ (D:\a\_actions\bxb100\action-upload\main\webpack:\upload-action\webpack\bootstrap:[21](https://github.com/sovzzz/SPT-AKI-SERVER-WEEKLY-BUILD/actions/runs/5500675136/jobs/10023737957#step:9:22):1)
    at Object.2381 (D:\a\_actions\bxb100\action-upload\main\webpack:\upload-action\node_modules\opendal\generated.js:91:1)
    at __nccwpck_require__ (D:\a\_actions\bxb100\action-upload\main\webpack:\upload-action\webpack\bootstrap:21:1)
    at Object.3880 (D:\a\_actions\bxb100\action-upload\main\webpack:\upload-action\node_modules\opendal\index.js:[22](https://github.com/sovzzz/SPT-AKI-SERVER-WEEKLY-BUILD/actions/runs/5500675136/jobs/10023737957#step:9:23):1)
    at __nccwpck_require__ (D:\a\_actions\bxb100\action-upload\main\webpack:\upload-action\webpack\bootstrap:21:1)
```
workflow file https://github.com/sovzzz/SPT-AKI-SERVER-WEEKLY-BUILD/actions/runs/5500675136/workflow
```
runs-on: windows-latest
```
```
      - name: Upload file to webdav
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.CT_ADDRESS }}
            username=${{ secrets.CT_EMAIL }}
            password=${{ secrets.CT_PASSWORD }}
            root=/test/
          include: 'project/Dockerfile'
```

**Comment by sovzzz** [comment]
it's also a problem that the older action https://github.com/bxb100/action-upload-webdav
didn't work when I use it.
it creates folders in WebDAV but don't upload files

**Comment by bxb100** [comment]
the previous version compiles in the local env, so it is missing the Windows binding.

I fixed it, and try to test it in the GitHub Action got success, so I hope the latest version can work on your workflow
